disabled_rules:
    - trailing_whitespace
    - type_body_length
    - line_length
    - file_length
    - function_body_length
    - function_parameter_count
    - force_cast
    - force_try
    - cyclomatic_complexity
identifier_name:
    min_length:
        error: 0
    allowed_symbols: ["_"]

excluded:
    - Pods
