use_frameworks!

platform :ios, '13.2'
# source 'https://github.com/tjlabs/jupiter-sdk-ios.git'

target 'JupiterSDK_Example' do
  use_frameworks!
#  pod 'JupiterSDK'
#  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'JupiterSDK', :path => '../'
  pod 'Alamofire'
  pod 'GoogleMaps', '4.0.0'
  pod 'GooglePlaces', '4.0.0'
  pod 'SnapKit' 

  target 'JupiterSDK_Tests' do
    inherit! :search_paths

  end
end
