use_frameworks!

platform :ios, '15.0'
source ‘https://github.com/CocoaPods/Specs.git’

target 'JupiterSDK_Example' do
  use_frameworks!
  pod 'JupiterSDK', :path => '../'
  pod 'OlympusSDK', '0.0.20'
  pod 'Alamofire'
  pod 'SwiftCSVExport' , '= 2.6.0'
  pod 'GoogleMaps', '4.0.0'
  pod 'GooglePlaces', '4.0.0'
  pod 'Charts' 
  pod 'SnapKit'
  pod 'ExpyTableView'
  pod 'Kingfisher'
  pod 'DropDown'
  pod 'Floaty', '~> 4.2.0'
  pod 'TextFieldEffects'
  pod 'AWSS3'
  pod 'SwiftLint', '0.55.1'
  
  pod 'FirebaseRemoteConfig'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  
  post_install do |installer|
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      end
    end
  end

  target 'JupiterSDK_Tests' do
    inherit! :search_paths

  end
end
