use_frameworks!

platform :ios, '13.2'
source 'https://github.com/tjlabs/jupiter-sdk-ios.git'

target 'JupiterSDK_Example' do
  pod 'JupiterSDK'
#  pod 'JupiterSDK', :path => '../'

  target 'JupiterSDK_Tests' do
    inherit! :search_paths

    
  end
end
